repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.11.0
    hooks:
      - id: air-format

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9003
    hooks:
      - id: roxygenize
        name: Regenerate documentation
      - id: use-tidy-description
        name: Format DESCRIPTION file
